export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const REMOVE_FLASH_MESSAGE = 'REMOVE_FLASH_MESSAGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';

export const ADD_IDEA_REQUEST = 'ADD_IDEA_REQUEST';
export const ADD_IDEA_SUCCESS = 'ADD_IDEA_SUCCESS';
export const ADD_IDEA_ERROR = 'ADD_IDEA_ERROR';

export const GET_SINGLE_IDEA_REQUEST = 'GET_SINGLE_IDEA_REQUEST';
export const GET_SINGLE_IDEA_SUCCESS = 'GET_SINGLE_IDEA_SUCCESS';
export const GET_SINGLE_IDEA_ERROR = 'GET_SINGLE_IDEA_ERROR';

export const EDIT_IDEA_REQUEST = 'EDIT_IDEA_REQUEST';
export const EDIT_IDEA_SUCCESS = 'EDIT_IDEA_SUCCESS';
export const EDIT_IDEA_ERROR = 'EDIT_IDEA_ERROR';

export const GET_PUBLIC_IDEAS_REQUEST = 'GET_PUBLIC_IDEAS_REQUEST';
export const GET_PUBLIC_IDEAS_SUCCESS = 'GET_PUBLIC_IDEAS_SUCCESS';
export const GET_PUBLIC_IDEAS_ERROR = 'GET_PUBLIC_IDEAS_ERROR';

export const GET_PERSONAL_IDEAS_REQUEST = 'GET_PERSONAL_IDEAS_REQUEST';
export const GET_PERSONAL_IDEAS_SUCCESS = 'GET_PERSONAL_IDEAS_SUCCESS';
export const GET_PERSONAL_IDEAS_ERROR = 'GET_PERSONAL_IDEAS_ERROR';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';

export const POST_IDEA_COMMENT_REQUEST = 'POST_IDEA_COMMENT_REQUEST';
export const POST_IDEA_COMMENT_SUCCESS = 'POST_IDEA_COMMENT_SUCCESS';
export const POST_IDEA_COMMENT_ERROR = 'POST_IDEA_COMMENT_ERROR';